FROM golang:1.4
#FROM golang:1.9
#FROM alpine:3.9

WORKDIR /root/goworkspace/compare/compareText/service/test
COPY . .
RUN go build -ldflags "-linkmode external -extldflags -static" -a main.go

FROM scratch
COPY --from=0 /root/goworkspace/compare/compareText/service/test/main
CMD ["/main"]
